trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'adriansilvaresramos'
    repository: 'adriansilvaresramos/microservicedata'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile.amd64'
